title: "Threat Intel Africa"
email: alerts@threatintel.africa
timezone: "Africa/Nairobi"
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Threat Intel Africa
paginate: 10
disqus: 'threatintel-africa'
formspree: 'xrgwdzpo'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: compressed
ganalytics: G-16PGTLNYBH

# Authors
authors:
  threatintelafrica:
    name: Threat Intel Africa
    display_name: Threat Intel Africa
    avatar: 'assets/images/logo.png'
    email: alerts@threatintel.africa
    website: https://threatintel.africa
    x: https://www.x.com/threatintelAF
    description: "African Tailored Threat Intelligence"

# Social
social:
  instagram: https://www.instagram.com/threatintelafrica
  linkedin: https://www.linkedin.com/company/threatintelafrica 
  github: http://github.com/tiafrica
  telegram: https://t.me/threatintelafrica
  x: https://x.com/threatintelAF
  facebook: https://facebook.com/threatintelafrica

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives